package:
  name: entropy
  version: "3.1a"

source:
  path: .

requirements:
  build:
    - fftw
  
  host:
    - python
    - setuptools
    - Cython
    - fftw
    - numpy x.x
  
  run:
    - python
    - fftw
    - numpy x.x

test:
  imports:
    - entropy
