package:
  name: xentropy
  version: "3.1a"

source:
  path: .

requirements:
  build:
    - fftw
    - python
  
  host:
    - python
    - setuptools
    - Cython
    - fftw
    - numpy x.x
  
  run:
    - fftw
    - numpy x.x
    - python

test:
  imports:
    - xentropy
