package:
  name: xentropy
  version: "3.1a"

source:
  path: .

requirements:
  build:
    - fftw
    - python
    - intel-openmp
    - {{ compiler('cxx') }}
  
  host:
    - python
    - fftw
    - setuptools
    - Cython
    - intel-openmp
  
  run:
    - fftw
    - numpy
    - python
    - intel-openmp

test:
  imports:
    - xentropy
