name: Python:Pip

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./package
      
    steps:
    - uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8


    - name: Install dependencies
      run: sudo apt-get install -y libfftw3-dev && pip install Cython

    - name: Build
      run: pip install -r requirements.txt; pip install .
      working-directory: ${{ env.working-directory }}

    #TODO: Run Tests
