name: Python:Pip

on:
  push:
    branches: [master]
  pull-request:
    branches: [master]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install fftw3
      run: sudo apt-get install -y libfftw3-dev

    - name: Build
      run: pip install .

    #TODO: Run Tests